== Committee IV.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu 4

Vaším úkolem za 5 bodů je vytvořit vlastní testy k balíčku `committee` pomocí frameworku
``pytest`` a knihovny ``betamax``. Není nutné použít ``flexmock``, pokud to nepotřebujete.

Námi dodávané testy jsou tz. _akceptační_, skoro až _integrační_. Testují aplikaci
z venku, jako black box a navíc proti živému API. Rozšiřte testovací sadu o testy
_jednotkové_: tedy testy, které testují vaše vlastní metody, funkce, třídy apod.
Vaše testy již nesmí komunikovat s reálným GitHub API.

NOTE: Pokud jste předchozí úkoly nedělali a nebo neprochází testy,
můžete použít https://github.com/cvut/committee/tree/v0.3[naše referenční řešení].

=== Podmínky:

* Testy lze spouštět pomocí `tox` a to nejen z gitu, ale i při rozbalení archivu `sdist`.
* Všechny testovací závislosti se musí při uvedeném příkazu nainstalovat.
** Je nutné správně rozlišit testovací a runtime závislosti.
* Testy samotné musí fungovat offline a bez nutnosti mít přístupové údaje k API.
* Spuštění testů i znovu-nahrání kazet musí být zdokumentováno v `README`. Je nutné umožnit všem znovunahrát kazety (tedy i lidem, kteří nemají přístup k vašemu GitHub účtu). Pro (znovu)vytvoření situace pro nahrání kazet můžete (ale nemusíte) použít (či upravit) skript `setup.sh` z našich současných testů.
* Nahrané kazety musí být v gitu a být součástí balíčku (ale neinstalují se).
* Žádné nahrané kazety (ani jiné soubory) nesmí obsahovat citlivé údaje.
* Alespoň část testu by měla být parametrická.
* Musí být použit nativní způsob pytest testů (pytest umí spouštět i testy pro `unittest` apod.).
* Testuje se všechno ++*++.
* Testy musí běžet i na https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python[GitHub Actions] (případně jiném veřejném CI).

+*+ Záměrně nestanovujeme podmínku na 100% pokrytí kódu testy.
Otestujte prostě kód tak, aby byly otestovány všechny podstatné součásti
včetně webové aplikace.

== Automatické testy

Námi dodané testy z minulých úloh jsou stále závazné, můžete (ale nemusíte) je
přibalit k vašim testům, ale musí být odděleny (jiná složka).

Následuje text z minula, který stále platí:

K úloze existuje sada testů.
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitářů. Pro jeho vytvoření použijte skript
`test_environment/setup.sh`. Je třeba nastavit proměnné prostředí
`GH_TOKEN` a `GH_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*.

Skript vytvoří na GitHubu 3 repozitáře:

 - committee-basic
 - committee-rules
 - committee-radioactive

Pokud by vám to vadilo, použijte testovací účet k tomuto určený.

Commit status nelze na GitHub smazat, tudíž jedinou možností, jak vyčistit
případný nepořádek je repozitáře smazat pomocí skriptu
`test_environment/delete.sh` (potřeba scope `delete_repo`) a vytvořit znovu.
Nicméně jsou testy napsané tak, že když jsou správně implementovány přepínače
`--dry-run` a `--force`, tak lze pouštět testy opakovaně bez nutnosti čistění
repozitářů.

Pro spuštění testů si do virtuálního prostředí si nainstalujte `pytest`,
nastavte stejné proměnné prostředí (`GH_TOKEN` a `GH_USER`) a spusťte `pytest`:

[source,console]
(__venv__) $ python -m pip install pytest
(__venv__) $ export GH_USER=anicka
(__venv__) $ export GH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
(__venv__) $ python -m pytest -v tests

Testy v souboru `test_radioactive_waste.py` trvají dlouho a mají potenciál
vyřadit vás na hodinu z přístupu ke GitHub API.
Když ladíte ostatní testy, doporučujeme je vypínat pomocí přepínače `-k`:

[source,console]
$ python -m pytest -v -k "not radioactive" test

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidávejte ale do repozitáře nikdy konfigurační soubory z `tests/fixtures/config`,
které se v průběhu testů vytváří a obsahují váš token.

Součástí výstupu selhaných testů je i kompletní způsob volání.

NOTE: Testy proti živému API a závisí tak na daném stavu repozitáře, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima.

WARNING: Splnění testů není nutnou ale pouze postačující podmínkou pro plný
počet bodů. Na druhou stranu lze odevzdat i úlohu, která neprojde všemi testy
pro získání alespoň adekvátní části bodů.

== Odevzdání úkolu

Úkol odevzdáváte tradičně s tagem `v0.4` a nahráním nové verze na testovací
PyPI. Použijte verzi 0.4 (případně 0.4.x v souladu s tagem).
