= Committee V.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu 5

Vaším úkolem za 5 bodů je vytvořit pomocí http://www.sphinx-doc.org[Sphinx]
dokumentaci k vašemu projektu `committee`.
(V ojedinělých případech je možné po e-mailové domluvě místo toho vytvořit 
dokumentaci k projektu `spacegrid`.)

Měla by obsahovat textovou část, ze které bude jasné, co je, k čemu je,
jak se nainstaluje a jak se používá vaše aplikace. Můžete předpokládat, že
uživatel ví, co je to GitHub, issue, commit, commit message, repozitář apod.
Nepředpokládejte ale, že ví, kde najde API token či webhook, že ví, co to je,
jak se k nim chovat apod.

Pokud hypoteticky ukážeme dokumentaci kolegům, kteří nikdy neviděli zadání
vašeho úkolu, musí to pro ně být stejně pochopitelné.

Dále by dokumentace měla obsahovat textovou část s ukázkami kódu, které se
testují pomocí doctestu. Tato část může vysvětlovat, jak váš kód použít pro
výrobu jiné aplikace, nebo může popisovat, jak aplikace uvnitř funguje.

V dokumentaci by měla existovat kapitola s *kompletní* API dokumentací vašich
modulů, tříd, funkcí apod. Všechny tyto věci musí mít v kódu dokumentační
řetězce, které v dokumentaci musí být zobrazeny (t.j. změna dokumentačního
řetězce se automaticky promítne ve vygenerované dokumentaci).

Jak sestavit a testovat dokumentaci by mělo být jasné z `README.rst`
(a to musí mít http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html[reStructuredText]
syntaxi).
`README.rst` musí obsahovat základní informace o projektu, pokročilejší věci
patří do Sphinx dokumentace.

Generování dokumentace ani doctesty nesmí způsobit chybu ani varování.
Potlačení chybových a varovných hlášek (např. konfigurací, přesměrováním
*stderr*, apod.) je povoleno jen po konzultaci s cvičícím.

Doctesty se musí automaticky spouštět na GitHub Actions (alternativně jiném CI).

Dokumentace musí být v angličtině.

Dosavadní funkcionalita aplikace musí být samozřejmě zachována.

Za fungující publikaci smysluplné dokumentace na https://readthedocs.org/[Read the Docs]
je možné získat bod navíc.

== Automatické testy

Námi dodané testy z minulých úloh jsou stále závazné.

Následuje text z minula, který stále platí:

K úloze existuje sada testů.
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitářů. Pro jeho vytvoření použijte skript
`test_environment/setup.sh`. Je třeba nastavit proměnné prostředí
`GH_TOKEN` a `GH_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*.

Skript vytvoří na GitHubu 3 repozitáře:

 - committee-basic
 - committee-rules
 - committee-radioactive

Pokud by vám to vadilo, použijte testovací účet k tomuto určený.

Commit status nelze na GitHub smazat, tudíž jedinou možností, jak vyčistit
případný nepořádek je repozitáře smazat pomocí skriptu
`test_environment/delete.sh` (potřeba scope `delete_repo`) a vytvořit znovu.
Nicméně jsou testy napsané tak, že když jsou správně implementovány přepínače
`--dry-run` a `--force`, tak lze pouštět testy opakovaně bez nutnosti čistění
repozitářů.

Pro spuštění testů si do virtuálního prostředí si nainstalujte `pytest`,
nastavte stejné proměnné prostředí (`GH_TOKEN` a `GH_USER`) a spusťte `pytest`:

[source,console]
(__venv__) $ python -m pip install pytest
(__venv__) $ export GH_USER=anicka
(__venv__) $ export GH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
(__venv__) $ python -m pytest -v tests

Testy v souboru `test_radioactive_waste.py` trvají dlouho a mají potenciál
vyřadit vás na hodinu z přístupu ke GitHub API.
Když ladíte ostatní testy, doporučujeme je vypínat pomocí přepínače `-k`:

[source,console]
$ python -m pytest -v -k "not radioactive" test

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidávejte ale do repozitáře nikdy konfigurační soubory z `tests/fixtures/config`,
které se v průběhu testů vytváří a obsahují váš token.

Součástí výstupu selhaných testů je i kompletní způsob volání.

NOTE: Testy proti živému API a závisí tak na daném stavu repozitáře, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima.

WARNING: Splnění testů není nutnou ale pouze postačující podmínkou pro plný
počet bodů. Na druhou stranu lze odevzdat i úlohu, která neprojde všemi testy
pro získání alespoň adekvátní části bodů.

== Odevzdání úkolu

Úkol odevzdáváte tradičně s tagem `v0.5` a nahráním nové verze na testovací
PyPI. Použijte verzi 0.5 (případně 0.5.x v souladu s tagem).
