== Committee III.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu 3

Vaším úkolem za 5 bodů je udělat z vašeho dosavadního projektu balíček
instalovatelný přes pip a nahrát jej na testovací PyPI.

Jelikož používáme všichni stejný název aplikace `committee`,
tak pro PyPI použijte jako název `committee_<username>`
(v reálných situacích se nedoporučuje jiný název než je jméno importovatelného modulu).

Pokud svůj kód za žádných okolností nechcete zveřejnit ani na testovací PyPI,
dejte nám vědět a domluvíme se.

NOTE: Pokud jste předchozí úkoly nedělali a nebo neprochází testy,
můžete použít https://github.com/cvut/committee/releases/tag/v0.2[naše referenční řešení].

Podmínky (je jich hodně, ale jsou triviální):

* Váš balíček musí fungovat (viz zadání předchozích úkolů)
  po instalaci pomocí pipu do „prázdného“ virtuálního prostředí.
  Musí tedy mít správně nadefinované všechny závislosti.
* Musí obsahovat rozumný počet classsifiers a voleb pro `setup.py`.
* Podpříkazy `sdist` a `bdist_wheel` nesmí skončit chybou ani vyvolat varování.
* Musí splňovat konvence uvedené ve výukových materiálech:
** Jméno importovatelného modulu musí být `committee` a všechny další pomocné
   moduly musí být jeho podmoduly.
** Všechny soubory `+__init__.py+` mají být víceméně prázdné a obsahovat pouze
   importy, případně nastavovat `+__all__+`.
** Verze balíčku musí odpovídat tagu. V případě iterování odevzdejte klidně verzi 0.3.x (kde x je např. 1, 2...).
* Hlavní program musí jít spouštět pomocí entrypointu `committee` i pomocí `-m committee`.
* Stále se musí dát z modulu `committee` přímo importovat Flask `app` (či `create_app`).
* Pokud jste již tak neučinili, tak rozdělte aplikaci na jednotlivé
  funkční celky. Měli byste mít alespoň 3 submoduly, například:
** `cli` - vstup + výpis na konzoli z prvního úkolu,
** `web` - flask aplikace,
** `github` - klient pro komunikaci s GitHub API (společný pro `cli` a
`web`),
** případně navíc ještě oddělit logiku práce se commity či další.
** (Pamatujte že v Pythonu není nutné každou třídu dávat do zvláštního souboru.
   Také připomínáme, že https://www.python.org/dev/peps/pep-0020/[Flat is better than nested],
   není tedy vhodné moduly do sebe nořit příliš hluboko.)
** Vyvarujte se cyklických importů!
* Zabalený modul musí obsahovat soubor s textem licence (`LICENSE`, `COPYING`) +*+
* `long_description` musí být dynamicky načten z `README`

+*+ Vhodnou licenci můžete najít na http://choosealicense.com/[choosealicense.com].
V případě, že váš kód nechcete šířit pod svobodnou licencí,
napište to do souboru vlastní podmínky. Nevymýšlejte si ale prosím vlastní
open-source licence.

== Automatické testy

Testy z minula byly mírně upraveny, aby nevolaly `python committee.py` přímo,
ale příkaz `committee`,
navíc byly přidány jednoduché testy, které volají `python -m committee`.

WARNING: Testy **netestují splnění tohoto úkolu**,
Testují pouze to, že se nic nerozbilo
a že funguje spuštění pomocí příkazů výše.

NOTE: Před spuštěním testů předpokládejte, že je váš balíček nainstalován.
Toho můžete docílit například pomocí `python setup.py develop`
nebo `pip install -e.`

Nově jsou dodány extra testy ve složce `test_module`, které simulují reálnou instalaci
vašeho balíčku `committee` z naklonovaného repozitáře i z testovací PyPI. Navíc testují
i další náležitosti požadované v tomto zadání (sdist bez warningů, submoduly, závislosti,
klíčová slova a další metadata). Tyto testy vyžadují nastavené proměnné prostředí
`CTU_USERNAME` a `COMMITTEE_REPO` pro získání vaší verze committee (pipem a gitem). V rámci
testů spouští subprocesy a pokud se na vašem OS jmenují jinak nebo jsou v jiné cestě, než
standardně na Linuxu, budete muset upravit soubor `fixtures/test_config.cfg`. V případě
potřeby založte issue. Tyto testy nepracují s aktuálním kódem „kolem nich“, ale s tím, co
je dostupné přes PyPI (publikováno) a GitHub (napushováno). Testy spustíte pomocí:

[source,console]
$ python -m pytest -v test_module

Následuje text z minula, který stále platí:

K úloze existuje sada testů.
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitářů. Pro jeho vytvoření použijte skript
`test_environment/setup.sh`. Je třeba nastavit proměnné prostředí
`GH_TOKEN` a `GH_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*.

Skript vytvoří na GitHubu 3 repozitáře:

 - committee-basic
 - committee-rules
 - committee-radioactive

Pokud by vám to vadilo, použijte testovací účet k tomuto určený.

Commit status nelze na GitHub smazat, tudíž jedinou možností, jak vyčistit
případný nepořádek je repozitáře smazat pomocí skriptu
`test_environment/delete.sh` (potřeba scope `delete_repo`) a vytvořit znovu.
Nicméně jsou testy napsané tak, že když jsou správně implementovány přepínače
`--dry-run` a `--force`, tak lze pouštět testy opakovaně bez nutnosti čistění
repozitářů.

Pro spuštění testů si do virtuálního prostředí si nainstalujte `pytest`,
nastavte stejné proměnné prostředí (`GH_TOKEN` a `GH_USER`) a spusťte `pytest`:

[source,console]
(__venv__) $ python -m pip install pytest
(__venv__) $ export GH_USER=anicka
(__venv__) $ export GH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
(__venv__) $ python -m pytest -v tests

Testy v souboru `test_radioactive_waste.py` trvají dlouho a mají potenciál
vyřadit vás na hodinu z přístupu ke GitHub API.
Když ladíte ostatní testy, doporučujeme je vypínat pomocí přepínače `-k`:

[source,console]
$ python -m pytest -v -k "not radioactive" test

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidávejte ale do repozitáře nikdy konfigurační soubory z `tests/fixtures/config`,
které se v průběhu testů vytváří a obsahují váš token.

Součástí výstupu selhaných testů je i kompletní způsob volání.

NOTE: Testy proti živému API a závisí tak na daném stavu repozitáře, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima.

WARNING: Splnění testů není nutnou ale pouze postačující podmínkou pro plný
počet bodů. Na druhou stranu lze odevzdat i úlohu, která neprojde všemi testy
pro získání alespoň adekvátní části bodů.

== Odevzdání úkolu

Odkazy na repozitář a balíček na testovací PyPI nám pošlete e-mailem.
Pro odevzdání v repozitáři nastavte tag `v0.3`, případně `v0.3.1`, `v0.3.2`...
