= Committee II.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu

Vaším úkolem za 5 bodů je rozšířit CLI  aplikaci z minulé úlohy o webové rozhraní.
Stávající funkcionalita ale musí být zachována, mimo původní aplikace půjde tedy
navíc spustit web server a to pomocí `flask run`.

Výslednou aplikaci nasaďte na https://www.pythonanywhere.com[PythonAnywhere],
nebo jiný veřejný https://www.python.org/dev/peps/pep-3333/[WSGI] hosting.
Odkaz na běžící aplikaci a repozitář nám pošlete e-mailem.

Vytvořte si repozitář `committee-web-test`, nastavte aplikaci, aby pracovala s tímto
repozitářem, a pozvěte nás (@hroncok, @MarekSuchanek) do něj, abychom mohli chování
vyzkoušet commitováním.

== Specifikace

- Aplikace musí přijímat na adrese `/` GitHub webhooky (metoda POST).
- Aplikace musí správně zpracovat
https://docs.github.com/en/developers/webhooks-and-events/about-webhooks[webhooky]
`push` a `ping` ve formátu JSON.

Na `ping` aplikace správně odpoví dle dokumentace.

Na `push` aplikace také správně odpoví dle dokumentace, navíc zpracuje příchozí commity
obsažené v poli `commits` dle konfiguračního souboru a zadání minulé úlohy. Nově se při
nastavování commit status pomocí webhooku bude mimo `status`, `context` a `description`
přidávat také `target_url` (URL, kde aplikace běží - nesmí být zadrátovaná).

Aplikace musí podporovat zabezpečení pomocí webhook secret (viz dále).

- Aplikace musí poskytovat na adrese `/` informace o nastavení (metoda GET).

Na adrese `/` se při požadavku GET bude nacházet jednoduchá HTML stránka,
ze které bude jasné, jaká pravidla platí, jaký je nastavený kontext a jaký uživatel
bude akce provádět. Uživatelské jméno se na stránce zobrazí podle použitého tokenu,
není zadrátované do kódu aplikace nebo šablony. Další obsah stránky je na vás.

Musíte využít šablonu. Nebudeme hodnotit vzhled stránky, ale využijte HTML pro
prezentaci informací. Vydumpování Python slovníku do `<pre>` boxu není dostačující.
Na stránce logicky nesmí být vidět `secret` ani `token`.

=== Spouštění aplikace

Aplikace se musí dát spustit z kořenového adresáře repozitáře pomocí příkazu `flask run`
a to nastavením proměnné prostředí `FLASK_APP` na `committee.py`.

[source,console]
$ export FLASK_APP=committee.py
$ flask run

Zároveň je možné pomocí proměnné prostředí nastavit,
kde má aplikace hledat konfigurační soubor(y).

Pomocí proměnné `COMMITTEE_CONFIG` je možné nastavit cestu ke konfiguračnímu souboru.

V konfiguračních souborech hledáte sekce `github`, `committee` a sekce s pravidly `rules`.
Chyby v konfiguraci se řeší identicky, jako v CLI aplikaci (hlášky a návratový kód).

CLI aplikace z minulého týdne musí stále fungovat a testy z minula musí procházet.

Webová aplikace bude pracovat defaultně s vypnutými `force` a `dry-run`. Dobrovolně můžete navíc
vyřešit detailní nastavování a zapínání force a dry-run například pomocí proměnných prostředí nebo
dalších konfiguračních voleb.

=== Zabezpečení webhooku

Protože příjímání událostí z internetu může být riskantní,
nabízí GitHub možnost webhooky zabezpečit proti zneužiti.
Abyste rozpoznali, že vám událost poslal právě GitHub,
je ke každému requestu z GitHubu přiložená hlavička `X-Hub-Signature`, např:

[source]
X-Hub-Signature: sha1=0b861d9a594a4f421cabcdef75d5aefc46df8967

která vám říká,
že pokud použijete HMAC hexdigest s odpovídající hash funkcí a s klíčem,
který je uvedený v položce `secret`, na celé tělo requestu
a vámi spočítaný výsledek se shoduje s tím v hlavičce `X-Hub-Signature`,
tak tento request přišel z GitHubu, a můžete mu tedy věřit.

Více informací a příklad v Ruby je na
https://developer.github.com/webhooks/securing/[github securing].

Do konfiguračního souboru (sekce `github`) tedy přidejte položku `secret`.
Při nastavování webhooku na GitHubu použijte stejný secret jako při nasazování
aplikace.

== Automatické testy

Testy z minula stále musí procházet.
Existuje i několik nových testů v souboru `test_web_smoke.py`.

Pro spuštění pouze nových testů můžete použít:

[source,console]
$ python -m pytest -v -k web tests

Pro nové testy není třeba speciální setup z minula.

WARNING: Testy **netestují hlavní funkcionalitu aplikace**,
ale pouze přidružené věci, jako importovatelnost,
přítomnost usernamu na hlavní stránce, ping, ověření „secret“.
Ujistěte se, že vaše nasazená aplikace funguje, jak má.

Následuje text z minula, který stále platí:

K úloze existuje sada testů.
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitářů. Pro jeho vytvoření použijte skript
`test_environment/setup.sh`. Je třeba nastavit proměnné prostředí
`GH_TOKEN` a `GH_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*.

Skript vytvoří na GitHubu 3 repozitáře:

 - committee-basic
 - committee-rules
 - committee-radioactive

Pokud by vám to vadilo, použijte testovací účet k tomuto určený.

Commit status nelze na GitHub smazat, tudíž jedinou možností, jak vyčistit
případný nepořádek je repozitáře smazat pomocí skriptu
`test_environment/delete.sh` (potřeba scope `delete_repo`) a vytvořit znovu.
Nicméně jsou testy napsané tak, že když jsou správně implementovány přepínače
`--dry-run` a `--force`, tak lze pouštět testy opakovaně bez nutnosti čistění
repozitářů.

Pro spuštění testů si do virtuálního prostředí si nainstalujte `pytest`,
nastavte stejné proměnné prostředí (`GH_TOKEN` a `GH_USER`) a spusťte `pytest`:

[source,console]
(__venv__) $ python -m pip install pytest
(__venv__) $ export GH_USER=anicka
(__venv__) $ export GH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
(__venv__) $ python -m pytest -v tests

Testy v souboru `test_radioactive_waste.py` trvají dlouho a mají potenciál
vyřadit vás na hodinu z přístupu ke GitHub API.
Když ladíte ostatní testy, doporučujeme je vypínat pomocí přepínače `-k`:

[source,console]
$ python -m pytest -v -k "not radioactive" tests

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidávejte ale do repozitáře nikdy konfigurační soubory z `tests/fixtures/config`,
které se v průběhu testů vytváří a obsahují váš token.

Součástí výstupu selhaných testů je i kompletní způsob volání.

NOTE: Testy proti živému API a závisí tak na daném stavu repozitáře, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima.

WARNING: Splnění testů není nutnou ale pouze postačující podmínkou pro plný
počet bodů. Na druhou stranu lze odevzdat i úlohu, která neprojde všemi testy
pro získání alespoň adekvátní části bodů.

== Odevzdání úkolu

Odkazy na repozitář a běžící aplikaci nám pošlete e-mailem.
Pro odevzdání v repozitáři nastavte tag `v0.2`.

